### ISSUE TITLE
Compiler tags are not removed

### ISSUE THREAD

**Issue by RaeesBhatti** [steelbrain/UCompiler#12]
Here is a repro case

``` js
//@compiler-output "../global.js"
//@compiler-transpile "true"
//@compiler-browserify "true"


require('./js-mods/lib/browser.js');
require('./general.js');
require('./tabs.js');
```

The output will still have the `//@compiler-output "../global.js"` tag.

**Comment by steelbrain** [comment]
I can not reproduce it on my linux line-endings, perhaps its windows only

**Comment by steelbrain** [comment]
Closing as changing the line-endings to linux solved the problem.

**Comment by RaeesBhatti** [comment]
Still having this issue.
The value of `contents` here https://github.com/steelbrain/UCompiler/blob/master/plugins/base.js#L39 is acutally corrent with the tag remvoed. So, I think some other value is being used in the output instead of this one.

**Comment by RaeesBhatti** [comment]
`//@compiler-include` in not being removed also, so, I think the problem is not limited to any specific tags.

**Comment by steelbrain** [comment]
Found the problem, a regex spacing problem :laughing:

**Comment by steelbrain** [comment]
Wait, that's not it. There's something else as well
