### ISSUE TITLE
Exclude PhpStorm's __jb_back__ files

### ISSUE THREAD

**Issue by RaeesBhatti** [steelbrain/UCompiler#13]
This is an example, `pandrah\\js\\src\\general.js___jb_bak___`. `uc-watch` will throw an error for file not found because it is create for a fraction of time only.

**Comment by RaeesBhatti** [comment]
Issue still not resolved.

**Comment by steelbrain** [comment]
will try to repro and fix

**Comment by steelbrain** [comment]
It was a typo.

**Comment by RaeesBhatti** [comment]
`___jb_old___` is also a JetBrains' file we need to exclude

**Comment by steelbrain** [comment]
Pushed the update.
