### ISSUE TITLE
Compression is limited to current file only

### ISSUE THREAD

**Issue by RaeesBhatti** [steelbrain/UCompiler#17]
`@compiler-compress "true"` should compress the output file not the current file.

**Comment by steelbrain** [comment]
Mind explaining it a bit more?

**Comment by RaeesBhatti** [comment]
The `@import` files in `.less` and `@compiler-include` files are not compressed by declaring `@compiler-compress "true"` in the parent file

**Comment by steelbrain** [comment]
Closing as a less.js bug, should be opened in their repo

**Comment by RaeesBhatti** [comment]
The correct way to compress imported css files is by importing them in following way

``` less
@import (less) "path/to/file.css";
```
