### ISSUE TITLE
Invalid path in CSS Maps

### ISSUE THREAD

**Issue by RaeesBhatti** [steelbrain/UCompiler#59]
It seems that CSS Maps have an extra `__source__` prepended to file paths. Like this

```
https://example.com/__source__/Assets/pandrah/src/less/general/animations.less
```

**Comment by steelbrain** [comment]
That is not invalid, and is done on purpose. There reason is that we can not have the same path for it a the dist file. It's a limitation by the specification of source maps.

I also did that to make the codebase clean, there are dist files, and then there's source files arranged differently
