### ISSUE TITLE
Support Source Maps

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/UCompiler#6]
Maybe inline them and not save them to a file?

**Comment by RaeesBhatti** [comment]
Standard way is to add the sourcemap comment at the end of the file with file url. Should be something like this.

```
//@compiler-sourcemap "style.css.map"
```

**Comment by steelbrain** [comment]
@raeesiqbal Any particular reason to not have them inline? I personally like inline as it doesn't create a whole new file just for the source map.

**Comment by RaeesBhatti** [comment]
Because it will not load the unneeded sourcemap if you don't have developer tools open.

**Comment by RaeesBhatti** [comment]
`//# sourceMappingURL=jquery.min.map` at the end of the file can be removed pretty easily if one wants to.

**Comment by steelbrain** [comment]
You use sourcemaps in development, and in development you open your dev tools all the times, it's not recommended for production files.

**Comment by RaeesBhatti** [comment]
Sourcemap should also be for production because if there is an error, one can easily track it down.

**Comment by steelbrain** [comment]
Now that's a good reason.

**Comment by RaeesBhatti** [comment]
bump!

**Comment by steelbrain** [comment]
Fixed by v3
