### ISSUE TITLE
Support multiple outputs

### ISSUE THREAD

**Issue by RaeesBhatti** [steelbrain/UCompiler#7]
Something like this
`//@compiler-output "something.css"`

`//@compiler-output "something.min.css" "compress: true"`
or

``` json
/*
[
  {  "output" : "something.css"},
  {  "output" : "something.min.css", "compress": true}
]
*/
```

**Comment by steelbrain** [comment]
This is gonna be complicated as we'll have to compile the same file multiple times to support this.

**Comment by RaeesBhatti** [comment]
What is complicated in this?

**Comment by steelbrain** [comment]
@raeesiqbal Currently we create one object and one string and pass it to all the transformers like

```
{
  internal: {
    file: {
      name: "",
      path: "",
      ext: ""
    }
  },
  Minify: true,
  Babel: true
},
"...contents..."
```

there's no way to fit that feature in this architecture, we'll have to rewrite all of it.

**Comment by RaeesBhatti** [comment]
There has to be a way my friend

**Comment by steelbrain** [comment]
Fixed by v3
