### ISSUE TITLE
Minify as an alias to "compress"

### ISSUE THREAD

**Issue by RaeesBhatti** [steelbrain/UCompiler#8]
`
//@compiler-minify "true"
`
should do same as
`
//@compiler-compress "true"
`

**Comment by steelbrain** [comment]
Well, we will have to support one, either minify or compress. The choice is yours.

**Comment by RaeesBhatti** [comment]
Why not both?

**Comment by steelbrain** [comment]
@raeesiqbal because then half of your codebase uses compress and half uses minify.

**Comment by RaeesBhatti** [comment]
Is there a problem in it?

**Comment by steelbrain** [comment]
Yes. For the love of mother cleanliness and for the hate of Mr confusion, we must choose one.

**Comment by RaeesBhatti** [comment]
Is this project open-source?

**Comment by steelbrain** [comment]
It's Source of Steel™
