### ISSUE TITLE
Initial tag space should be optional

### ISSUE THREAD

**Issue by RaeesBhatti** [steelbrain/UCompiler#9]
`
//@compiler-something "true"
`
should be same as
`
//@ compiler-something "true"
`

**Comment by steelbrain** [comment]
This just looks unclean.

**Comment by RaeesBhatti** [comment]
It looks better in my opinion

**Comment by steelbrain** [comment]
```
// @Compiler-Transpile "true"

//@ Compiler-Transpile "true"
```

The first one looks cleaner. I mean, ask a third person

**Comment by RaeesBhatti** [comment]
`//@compiler-transpile "true"` looks much cleaner

**Comment by steelbrain** [comment]
It's already that way by the way.
